# -*- coding: utf-8 -*-
"""pandas step(문제).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17d_1QOjwp1KrWieWPHolnFi5KM97w-jA
"""

import pandas as pd

# DB api 호출을 통한 데이터 프레임 생성
from impala.dbapi import connect
import pandas as pd

# Step 1: Impala 연결 설정
conn = connect(
    host='apramn102.hyundaicapital.com',  # Hue에서 사용하는 Impala 호스트 주소
    port=21053,               # Impala 기본 포트
    auth_mechanism='GSSAPI'   # 사용할 데이터베이스 이름
)

# Step 2: SQL 쿼리 실행 및 DataFrame으로 변환
query = "SELECT * FROM hcs_t_bdpedu_l2a.bankchurners;"
df = pd.read_sql(query, conn)

# Step 3: 데이터프레임 확인
print(df)

# Step 4: 연결 닫기
conn.close()

# 5p
# 기술통계량이란 count, min, max 등의 통계지표를 의미합니다

# 6p
# drop 메서드를 사용하여 컬럼을 삭제해봅니다
# 삭제 컬럼 대상 : Contacts_Count_12_mon, Months_Inactive_12_mon
# inplace = True을 사용하여 원본 데이터에 변경

# 7p
# 1. 결측치 존재 여부를 확인합니다.

# 7p
# 2. fillna 메서드를 사용하여 결측치가 존재하는 Customer_Age 컬럼에 한정하여, 결측치를 평균값으로 대체해봅니다
# inplace = True을 사용하여 원본 데이터에 변경

# 7p
# 결측치가 정상적으로 대체되었는지 확인하기위해 코드를 실행해봅니다
df.isnull().sum()

import matplotlib.pyplot as plt
import seaborn as sns

# 8p
# Customer_Age 컬럼을 box plot으로 시각화하여 이상치 존재 여부를 확인해봅니다.

# 9p
# Attrition_Flag 컬럼을 원-핫 인코딩하여 수치형 변수로 변경해봅니다.