# -*- coding: utf-8 -*-
"""matplotlib step(정답).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q7xrfGlWHUp1D2Aao4uvRxnxe6NhZSBg
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# DB api 호출을 통한 데이터 프레임 생성
from impala.dbapi import connect
import pandas as pd

# Step 1: Impala 연결 설정
conn = connect(
    host='apramn102.hyundaicapital.com',  # Hue에서 사용하는 Impala 호스트 주소
    port=21053,               # Impala 기본 포트
    auth_mechanism='GSSAPI'   # 사용할 데이터베이스 이름
)

# Step 2: SQL 쿼리 실행 및 DataFrame으로 변환
query = "SELECT * FROM hcs_t_bdpedu_l2a.bankchurners;"
df = pd.read_sql(query, conn)

# Step 3: 데이터프레임 확인
print(df)

# Step 4: 연결 닫기
conn.close()

# 10p
# customer_age 컬럼을 이용하여 히스토그램을 그려봅니다.
# 빈도수는 20으로 지정합니다.
plt.hist(df['customer_age'], bins=20)
plt.show()

# 11p
# credit_limit 과 avg_utilization_ratio 컬럼을 사용하여 관계를 산점도로 그려봅니다.
# x축 이름은 credit_limit
# y축 이름은 avg utilization ratio
plt.scatter(df['credit_limit'], df['avg_utilization_ratio'])
plt.xlabel('credit_limit')
plt.ylabel('avg utilization ratio')
plt.show()

# 12p
# Bankchruners 데이터프레임에서 수치형 변수에 해당하는 컬럼만 대상으로 상관계수를 구해봅니다.
df.corr(numeric_only=True)

# 12p
# 상관계수를 시각화해봅니다.
plt.figure(figsize=(16,9))
sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.show()